# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Project1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StudentTestGUI(object):
    def setupUi(self, StudentTestGUI):
        StudentTestGUI.setObjectName("StudentTestGUI")
        StudentTestGUI.resize(450, 450)
        StudentTestGUI.setMinimumSize(QtCore.QSize(450, 450))
        StudentTestGUI.setMaximumSize(QtCore.QSize(450, 450))
        StudentTestGUI.setMouseTracking(False)
        StudentTestGUI.setAutoFillBackground(False)
        StudentTestGUI.setStyleSheet("border-color: rgb(255, 3, 15);\n"
"background-color: rgb(239, 241, 255);")
        self.centralwidget = QtWidgets.QWidget(StudentTestGUI)
        self.centralwidget.setObjectName("centralwidget")
        self.gradecalclabel = QtWidgets.QLabel(self.centralwidget)
        self.gradecalclabel.setGeometry(QtCore.QRect(110, 0, 221, 51))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.gradecalclabel.setFont(font)
        self.gradecalclabel.setObjectName("gradecalclabel")
        self.studentnuminput = QtWidgets.QLineEdit(self.centralwidget)
        self.studentnuminput.setGeometry(QtCore.QRect(200, 120, 181, 21))
        self.studentnuminput.setObjectName("studentnuminput")
        self.testscoresinput = QtWidgets.QLineEdit(self.centralwidget)
        self.testscoresinput.setGeometry(QtCore.QRect(200, 170, 181, 22))
        self.testscoresinput.setObjectName("testscoresinput")
        self.studentnumlabel = QtWidgets.QLabel(self.centralwidget)
        self.studentnumlabel.setGeometry(QtCore.QRect(70, 120, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.studentnumlabel.setFont(font)
        self.studentnumlabel.setObjectName("studentnumlabel")
        self.scoreslabel = QtWidgets.QLabel(self.centralwidget)
        self.scoreslabel.setGeometry(QtCore.QRect(40, 170, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.scoreslabel.setFont(font)
        self.scoreslabel.setObjectName("scoreslabel")
        self.studentscoresprintlabel = QtWidgets.QLabel(self.centralwidget)
        self.studentscoresprintlabel.setGeometry(QtCore.QRect(10, 270, 421, 181))
        self.studentscoresprintlabel.setMinimumSize(QtCore.QSize(421, 181))
        self.studentscoresprintlabel.setMaximumSize(QtCore.QSize(421, 181))
        self.studentscoresprintlabel.setText("")
        self.studentscoresprintlabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.studentscoresprintlabel.setObjectName("studentscoresprintlabel")
        self.Calculatorbutton = QtWidgets.QPushButton(self.centralwidget)
        self.Calculatorbutton.setGeometry(QtCore.QRect(40, 220, 111, 28))
        self.Calculatorbutton.setObjectName("Calculatorbutton")
        self.Clearbutton = QtWidgets.QPushButton(self.centralwidget)
        self.Clearbutton.setGeometry(QtCore.QRect(280, 220, 111, 28))
        self.Clearbutton.setObjectName("Clearbutton")
        StudentTestGUI.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(StudentTestGUI)
        self.statusbar.setObjectName("statusbar")
        StudentTestGUI.setStatusBar(self.statusbar)

        self.retranslateUi(StudentTestGUI)
        QtCore.QMetaObject.connectSlotsByName(StudentTestGUI)

    def retranslateUi(self, StudentTestGUI):
        _translate = QtCore.QCoreApplication.translate
        StudentTestGUI.setWindowTitle(_translate("StudentTestGUI", "Student Test Grades"))
        self.gradecalclabel.setText(_translate("StudentTestGUI", "Grade Calculator"))
        self.studentnumlabel.setText(_translate("StudentTestGUI", "# Of Students:"))
        self.scoreslabel.setText(_translate("StudentTestGUI", "Student Test Scores:"))
        self.Calculatorbutton.setText(_translate("StudentTestGUI", "Calculate Grades"))
        self.Clearbutton.setText(_translate("StudentTestGUI", "Clear Inputs"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StudentTestGUI = QtWidgets.QMainWindow()
    ui = Ui_StudentTestGUI()
    ui.setupUi(StudentTestGUI)
    StudentTestGUI.show()
    sys.exit(app.exec_())
